### ISSUE TITLE
Environment for Crawler not detected

### ISSUE THREAD

**Issue by benyaminl** [goFrendiAsgard/ubhara-workshop#1]
Hello I'm Benyamin, I'm working under Mrs. Maryati supervision at STTS.edu/iSTTS.ac.id.

I want to ask, I got problem with https://github.com/goFrendiAsgard/ubhara-workshop/blob/master/docker-compose.yml#L65 env for crawler container. The weird thing is, the postgres container env running fine (Other container, only crawler container).

It always result on source not found (the .bashrc not found btw). 2nd thing to access the postgress I need manually run the python main.py, and get the docker host IP first (thank God it can be accessed), using `docker inspect $(folder name)_postgres_1`. 

see 
```sh
ben@maryati:/home/maryati/workshop$ docker logs workshop_crawler_1
no change     /opt/conda/condabin/conda
no change     /opt/conda/bin/conda
no change     /opt/conda/bin/conda-env
no change     /opt/conda/bin/activate
no change     /opt/conda/bin/deactivate
no change     /opt/conda/etc/profile.d/conda.sh
no change     /opt/conda/etc/fish/conf.d/conda.fish
no change     /opt/conda/shell/condabin/Conda.psm1
no change     /opt/conda/shell/condabin/conda-hook.ps1
no change     /opt/conda/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /opt/conda/etc/profile.d/conda.csh
modified      /root/.bashrc

==> For changes to take effect, close and re-open your current shell. <==

/bin/sh: 1: source: not found
no change     /opt/conda/condabin/conda
no change     /opt/conda/bin/conda
no change     /opt/conda/bin/conda-env
no change     /opt/conda/bin/activate
no change     /opt/conda/bin/deactivate
no change     /opt/conda/etc/profile.d/conda.sh
no change     /opt/conda/etc/fish/conf.d/conda.fish
no change     /opt/conda/shell/condabin/Conda.psm1
no change     /opt/conda/shell/condabin/conda-hook.ps1
no change     /opt/conda/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /opt/conda/etc/profile.d/conda.csh
no change     /root/.bashrc
No action taken.
/bin/sh: 1: source: not found
```

so in the end I run the docker container manually, get the IP of the postgres first, and export the env one by one on the bash terminal and tun python main.py
eg. 
```sh
ben@maryati:~$ docker inspect workshop_postgres_1
... output omited
"Networks": {
                "workshop_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "3e8cb10fc010",
                        "postgres"
                    ],
                    "NetworkID": "15d457b9e3bc28b7f63f29f0ee738bdc94c2583b2533684b0bb0dc60176473e8",
                    "EndpointID": "146a70220db46ce280983a5a5eb10e6d4b9e10b72bfec3ecfcdaf8f73437a359",
                    "Gateway": "172.19.0.1",
                    "IPAddress": "172.19.0.2",
                    "IPPrefixLen": 16,
... output omited(take the Gateway Adderess)

(base) root@cd3399520ee0:/home/anaconda# export TWITTER_ACCESS_TOKEN=(secret)
(base) root@cd3399520ee0:/home/anaconda# export TWITTER_ACCESS_TOKEN_SECRET=(secret)
(base) root@cd3399520ee0:/home/anaconda#
(base) root@cd3399520ee0:/home/anaconda# export TWITTER_CONSUMER_KEY=(secret)
(base) root@cd3399520ee0:/home/anaconda# export TWITTER_CONSUMER_SECRET=(secret)
(base) root@cd3399520ee0:/home/anaconda#
(base) root@cd3399520ee0:/home/anaconda# export PYTHONUNBUFFERED=1
(base) root@cd3399520ee0:/home/anaconda#
(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_USER=postgresUser
(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_DATABASE=postgres
(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_SCHEMA=tweet
(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_PASSWORD=postgresPassword
(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_HOST=postgres
(base) root@cd3399520ee0:/home/anaconda#
(base) root@cd3399520ee0:/home/anaconda# export REDASH_LOG_LEVEL=INFO
(base) root@cd3399520ee0:/home/anaconda# export REDASH_REDIS_URL=redis://redis:6379/0
(base) root@cd3399520ee0:/home/anaconda# export REDASH_COOKIE_SECRET=5vTYwAGozxFfaFJebCjk0GNbVCvPCq0L
(base) root@cd3399520ee0:/home/anaconda# export REDASH_SECRET_KEY=k2MbEnRzeykVo1oojrXwwlHcLOzImzht
(base) root@cd3399520ee0:/home/anaconda# export REDASH_DATABASE_URL=postgresql://postgresUser:postgresPassword@postgres/postgres

(base) root@cd3399520ee0:/home/anaconda# python main.py
CREATE POSTGRES SCHEMA
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    create_postgres_schema()
  File "main.py", line 39, in create_postgres_schema
    connection = create_connection()
  File "main.py", line 34, in create_connection
    return psycopg2.connect(
  File "/opt/conda/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_HOST=postgres_1
(base) root@cd3399520ee0:/home/anaconda# python main.py
CREATE POSTGRES SCHEMA
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    create_postgres_schema()
  File "main.py", line 39, in create_postgres_schema
    connection = create_connection()
  File "main.py", line 34, in create_connection
    return psycopg2.connect(
  File "/opt/conda/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres_1" to address: Name or service not known

(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_HOST=172.17.0.2
(base) root@cd3399520ee0:/home/anaconda# python main.py
CREATE POSTGRES SCHEMA
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    create_postgres_schema()
  File "main.py", line 39, in create_postgres_schema
    connection = create_connection()
  File "main.py", line 34, in create_connection
    return psycopg2.connect(
  File "/opt/conda/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "172.17.0.2" and accepting
        TCP/IP connections on port 5432?

(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_HOST=172.19.0.2
(base) root@cd3399520ee0:/home/anaconda# python main.py
CREATE POSTGRES SCHEMA
Traceback (most recent call last):
  File "main.py", line 88, in <module>
    create_postgres_schema()
  File "main.py", line 39, in create_postgres_schema
    connection = create_connection()
  File "main.py", line 34, in create_connection
    return psycopg2.connect(
  File "/opt/conda/lib/python3.8/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out
        Is the server running on host "172.19.0.2" and accepting
        TCP/IP connections on port 5432?

(base) root@cd3399520ee0:/home/anaconda# export POSTGRES_HOST=172.17.0.1
(base) root@cd3399520ee0:/home/anaconda# python main.py
CREATE POSTGRES SCHEMA
CREATE CONNECTION
CREATE STREAM
START STREAM
ID:  1253177339330146306
FULL_TEXT: Once upon a time the whole shebang gave the feeling of being relaxed. The warm south would subtract patchouly. Nonetheless, the alligator sustained sprightly. Next, the want instantly liked; and once again, those who tighten burst billy. The end.
HASHTAGS:  []
USER_ID: 1166682001044377601
USER_NAME: Stories For Smell �
RETWEET_COUNT:  0
REPLY_COUNT:  0
CREATED AT:  2020-04-23 04:22:15
======================================
ID:  1253177339325722624
FULL_TEXT: The problem, for me, is when humans misrepresent our agency about/towards/regarding the Earth (which is obviously immense: the Anthropocene is very real). Of course we affect the Earth, possibly to a degree that will make it unlivable for many of the living things on it today.
HASHTAGS:  []
USER_ID: 2316384882
USER_NAME: Jeff Guhin
RETWEET_COUNT:  0
REPLY_COUNT:  0
CREATED AT:  2020-04-23 04:22:15
======================================

.. output omited
```

Anyway do you have any idea sir about this matter? since I seen the yml file it's fine and shouldn't be any problem with it. 

This's the brief of my machine, thank you. 
```
ben@maryati:/home/maryati/workshop/crawler$ docker -v
Docker version 19.03.6, build 369ce74a3c
Docker version 19.03.6, build 369ce74a3c
ben@maryati:/home/maryati/workshop/crawler$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

**Comment by goFrendiAsgard** [comment]
Hello, do you use `docker-compose up` or do you perform `docker start` manually for each containers?

**Comment by benyaminl** [comment]
> Hello, do you use `docker-compose up` or do you perform `docker start` manually for each containers?
I did `docker-compose up`, 
see the 
```sh
no change     /opt/conda/condabin/conda
no change     /opt/conda/bin/conda
no change     /opt/conda/bin/conda-env
no change     /opt/conda/bin/activate
no change     /opt/conda/bin/deactivate
no change     /opt/conda/etc/profile.d/conda.sh
no change     /opt/conda/etc/fish/conf.d/conda.fish
no change     /opt/conda/shell/condabin/Conda.psm1
no change     /opt/conda/shell/condabin/conda-hook.ps1
no change     /opt/conda/lib/python3.8/site-packages/xontrib/conda.xsh
no change     /opt/conda/etc/profile.d/conda.csh
no change     /root/.bashrc
No action taken.
/bin/sh: 1: source: not found
```

the `/bin/sh: 1: source: not found` because no /home/anaconda/.bashrc, I tried to add the .bashrc because on your Dockerfile https://github.com/goFrendiAsgard/ubhara-workshop/blob/master/crawler/Dockerfile#L10 you did copy the whole file inside the folder, so I add the .bashrc but no luck 🔢 hahaha.. I forgot to try the remove the `source` command, after I remove it, it run flawlessly. _Anyway I wanted to know, why you do source the .bashrc when there's no .bashrc? Or it's specific for some OS?_ 

#from freenode #docker
![image](https://user-images.githubusercontent.com/2817332/80062823-ccf13000-855e-11ea-962d-bac81b7bdf77.png)


Seems the problem is simple sir, It's just the bashrc not detected on the dockerfile, please review the Dockerfile changes. Thank you

*last try, I already tried to add .bashrc, but seems /bin/sh (the normal shell), never know .bashrc
related to https://unix.stackexchange.com/a/44619/356335

now the crawler are running anyway. Thank you 
![image](https://user-images.githubusercontent.com/2817332/80064059-6cafbd80-8561-11ea-87a4-d8a4eeb22926.png)

![image](https://user-images.githubusercontent.com/2817332/80064048-66214600-8561-11ea-908e-928ce492d13c.png)

**Comment by goFrendiAsgard** [comment]
Hello, glad you solved it. It is kind of strange because I use the same command in almost all conda-based docker image.

I will try out your PR. It is going to be great if we don't need to run bashrc.

Thank you for contributing and giving feedback 👍

**Comment by goFrendiAsgard** [comment]
As for your question:

>  Anyway I wanted to know, why you do source the .bashrc when there's no .bashrc? Or it's specific for some OS?

I really think the `.bashrc` should be there, since crawler's dockerfile was based on this one: https://hub.docker.com/r/continuumio/miniconda3/dockerfile. And if you look at the definition, this command should create `.bashrc`

```
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc
```

**Comment by benyaminl** [comment]
> As for your question:
> 
> > Anyway I wanted to know, why you do source the .bashrc when there's no .bashrc? Or it's specific for some OS?
> 
> I really think the `.bashrc` should be there, since crawler's dockerfile was based on this one: https://hub.docker.com/r/continuumio/miniconda3/dockerfile. And if you look at the definition, this command should create `.bashrc`
> 
> ```
> RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh && \
>     /bin/bash ~/miniconda.sh -b -p /opt/conda && \
>     rm ~/miniconda.sh && \
>     /opt/conda/bin/conda clean -tipsy && \
>     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
>     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
>     echo "conda activate base" >> ~/.bashrc
> ```

Nah that should be, but when I debug, with you dockerfile, it's broken. I still don't know why. I also think that when I seen the anaconda cmd, but when I run, it doesn't create it at all. 
I will try it on another machine first. Let me contact you back. Thank you sir.
